version: 3

tasks:
  build:
    desc: "build the project"
    cmds: 
    - GOFLAGS=-mod=mod go build -o bin/time-tracker main.go

  run:
    desc: "run the project"
    cmds: 
    - GOFLAGS=-mod=mod go run main.go
